---
branches:
  only:
  - master

# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: osx
      language: generic
      install:
        # Workaround for OSX.
        - sudo pip install -U setuptools
        - sudo pip install ansible
        - bundle install
      env:
        - TARGET=localhost
        # Workaround for OSX.
        - PYTHONPATH="/Library/Python/2.7/site-packages:$PYTHONPATH"

# This role needs sudo, thus we can't use the new container infrastructure
# sudo: false
sudo: required

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -l ${TARGET} -vvvv
  - bundle exec rake spec SPEC_TARGET=${TARGET}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
