---
# tasks file for homebrew(On OSX)
- name: Create a directory for homebrew
  file:
    path: "{{ homebrew_prefix }}"
    state: "directory"
    owner: "{{ ansible_user_id }}"
    group: "admin"
    mode: "0755"
  become: yes
- name: Clone homebrew
  git:
    repo: "git://github.com/Homebrew/homebrew.git"
    dest: "{{ homebrew_prefix }}"
    accept_hostkey: yes
    update: no
- name: Update homebrew
  command: "{{ homebrew_prefix }}/bin/brew update"
  register: result_homebrew_update
  changed_when: "'No changes to formulae' not in result_homebrew_update.stdout"
